//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddIn
    {
        public int Pk_AddInId { get; set; }
        public Nullable<int> Fk_IntegratorId { get; set; }
        public Nullable<bool> ItemImport { get; set; }
        public Nullable<bool> ItemExport { get; set; }
        public Nullable<bool> PriceImport { get; set; }
        public Nullable<bool> PriceExport { get; set; }
        public Nullable<bool> InventoryImport { get; set; }
        public Nullable<bool> InventoryExport { get; set; }
        public Nullable<bool> ImagesImport { get; set; }
        public Nullable<bool> ImagesExport { get; set; }
        public Nullable<bool> OrdersImport { get; set; }
        public Nullable<bool> OrdersExport { get; set; }
        public Nullable<bool> BillingImport { get; set; }
        public Nullable<bool> BillingExport { get; set; }
        public Nullable<bool> ShipmentsImport { get; set; }
        public Nullable<bool> ShipmentsExport { get; set; }
        public Nullable<bool> RefundsImport { get; set; }
        public Nullable<bool> RefundsExport { get; set; }
        public Nullable<bool> ReturnsImport { get; set; }
        public Nullable<bool> ReturnsExport { get; set; }
        public Nullable<bool> CancellationImport { get; set; }
        public Nullable<bool> CancellationExport { get; set; }
        public string ItemImportApi { get; set; }
        public string MatrixItemImportApi { get; set; }
        public string KitItemImportApi { get; set; }
        public string ItemGroupImportApi { get; set; }
        public string ItemExportApi { get; set; }
        public string MatrixItemExportApi { get; set; }
        public string KitItemExportApi { get; set; }
        public string ItemGroupExportApi { get; set; }
        public string PriceImportApi { get; set; }
        public string PriceExportApi { get; set; }
        public string InventoryImportApi { get; set; }
        public string InventoryExportApi { get; set; }
        public string ImagesImportApi { get; set; }
        public string ImagesExportApi { get; set; }
        public string OrdersImportApi { get; set; }
        public string OrdersExportApi { get; set; }
        public string BillingImportApi { get; set; }
        public string OrderInvoiceApi { get; set; }
        public string OrderCashSaleApi { get; set; }
        public string BillingExportApi { get; set; }
        public string ShipmentsImportApi { get; set; }
        public string ShipmentsExportApi { get; set; }
        public string RefundsImportApi { get; set; }
        public string RefundsExportApi { get; set; }
        public string ReturnsImportApi { get; set; }
        public string ReturnsExportApi { get; set; }
        public string CancellationImportApi { get; set; }
        public string CancellationExportApi { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Fk_ERPID { get; set; }
    }
}
