//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonCredential
    {
        public int Pk_id { get; set; }
        public string Country { get; set; }
        public string developerid { get; set; }
        public string region { get; set; }
        public string aws_accesskey { get; set; }
        public string aws_secretkey { get; set; }
    }
}
