//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Connector()
        {
            this.UserConnectors = new HashSet<UserConnector>();
        }
    
        public int PK_ConnectorID { get; set; }
        public string ConnectorName { get; set; }
        public string LogoPath { get; set; }
        public string dashboardName { get; set; }
        public string CredentialHeaders { get; set; }
        public string CredentialHeadersDisplay { get; set; }
        public string ConnectorFieldMapping { get; set; }
        public string FlowNames { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
        public string OverView { get; set; }
        public Nullable<int> FK_ConnectorType { get; set; }
        public string FAQ { get; set; }
        public string ConnectorLogo { get; set; }
        public string APIName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConnector> UserConnectors { get; set; }
    }
}
