//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public int PK_ID { get; set; }
        public Nullable<int> Fk_IntegratorID { get; set; }
        public string fieldName { get; set; }
        public string scriptId { get; set; }
        public string DataType { get; set; }
    }
}
