//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSubscription
    {
        public int PK_CustomerSubscriptionID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> FK_SubscriptionID { get; set; }
        public Nullable<int> FK_UserConnectorID { get; set; }
        public Nullable<bool> IsAddDashboard { get; set; }
        public Nullable<int> Fk_ConnectorID { get; set; }
        public string LicenseKey { get; set; }
        public string ApplicationCode { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> Fk_ERPID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SubscriptionPlan SubscriptionPlan { get; set; }
    }
}
