//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultMapping
    {
        public int Pk_MappingID { get; set; }
        public Nullable<int> Fk_ConnectorID { get; set; }
        public string Item_ImportFieldsMapping { get; set; }
        public string Item_ExportFieldsMapping { get; set; }
        public string Inventory_ImportFieldsMapping { get; set; }
        public string Inventory_ExportFieldsMapping { get; set; }
        public string Price_ImportFieldsMapping { get; set; }
        public string Price_ExportFieldsMapping { get; set; }
        public string Image_ImportFieldsMapping { get; set; }
        public string Image_ExportFieldsMapping { get; set; }
        public string Orders_ImportFieldsMapping { get; set; }
        public string Orders_ExportFieldsMapping { get; set; }
        public string Shipments_ImportFieldsMapping { get; set; }
        public string Shipments_ExportFieldsMapping { get; set; }
        public string Refunds_ImportFieldsMapping { get; set; }
        public string Refunds_ExportFieldsMapping { get; set; }
        public string Cancellation_ImportFieldsMapping { get; set; }
        public string Cancellation_ExportFieldsMapping { get; set; }
        public string Billing_ImportFieldsMapping { get; set; }
        public string Billing_ExportFieldsMapping { get; set; }
        public string Orders_AdvanceFieldMapping { get; set; }
    }
}
