//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionLog
    {
        public int SNo { get; set; }
        public Nullable<int> IntegratorID { get; set; }
        public string ProcessName { get; set; }
        public string LogType { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
