//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.RefreshTokens = new HashSet<RefreshToken>();
        }
    
        public int PK_LoginID { get; set; }
        public Nullable<int> Fk_RoleID { get; set; }
        public Nullable<int> Fk_UserId { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LoginAccessToken { get; set; }
        public Nullable<bool> EmailVerify { get; set; }
        public string FullName { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Role Role2 { get; set; }
        public virtual Role Role3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefreshToken> RefreshTokens { get; set; }
    }
}
