//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetSuiteStandardField
    {
        public int PK_NSF_ID { get; set; }
        public string Record { get; set; }
        public string FieldName { get; set; }
        public string ScriptId { get; set; }
        public string FieldType { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> IsImport { get; set; }
    }
}
