//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnersign
    {
        public int Pk_PartnerSignId { get; set; }
        public string redirect_uri { get; set; }
        public string amazon_state { get; set; }
        public string state { get; set; }
    }
}
