//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequest
    {
        public int PK_QuoteID { get; set; }
        public Nullable<int> Fk_CustomerID { get; set; }
        public Nullable<int> Fk_loginID { get; set; }
        public Nullable<int> Fk_connectorID { get; set; }
        public string CompanyName { get; set; }
        public string BusinessDescription { get; set; }
        public string Requirements { get; set; }
        public Nullable<int> QuoteStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
