//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public string ID { get; set; }
        public string UserName { get; set; }
        public string ClientID { get; set; }
        public Nullable<System.DateTime> IssuedTime { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public string ProtectedTicket { get; set; }
        public Nullable<int> Fk_CustomerId { get; set; }
        public Nullable<int> Fk_UserId { get; set; }
        public Nullable<int> Fk_LoginId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Login Login { get; set; }
        public virtual User User { get; set; }
    }
}
