//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetUpRecord
    {
        public int PK_SETUP_ID { get; set; }
        public int FK_Integratorid { get; set; }
        public string OrderNumber { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> Fk_ERPID { get; set; }
        public string OrderImportDate { get; set; }
        public string ShipmentDate { get; set; }
        public string ShipmentID { get; set; }
        public Nullable<bool> RunSuiteScriptAndWorkflow { get; set; }
        public Nullable<int> ShippingTaxCode { get; set; }
        public Nullable<int> ProductTaxCode { get; set; }
        public string CancelShipmentDate { get; set; }
        public string RelistItemDate { get; set; }
    }
}
