//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionPlan()
        {
            this.CustomerSubscriptions = new HashSet<CustomerSubscription>();
        }
    
        public int PK_SubscriptionID { get; set; }
        public Nullable<int> FK_ConnectorID { get; set; }
        public Nullable<int> SubscriptionType { get; set; }
        public string SubscriptionName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SubscriptionCost { get; set; }
        public Nullable<bool> Item_Import { get; set; }
        public Nullable<bool> Item_Export { get; set; }
        public Nullable<bool> Inventory_Import { get; set; }
        public Nullable<bool> Inventory_Export { get; set; }
        public Nullable<bool> Price_Import { get; set; }
        public Nullable<bool> Price_Export { get; set; }
        public Nullable<bool> Image_Import { get; set; }
        public Nullable<bool> Image_Export { get; set; }
        public Nullable<bool> Orders_Import { get; set; }
        public Nullable<bool> Orders_Export { get; set; }
        public Nullable<bool> Shipments_Import { get; set; }
        public Nullable<bool> Shipments_Export { get; set; }
        public Nullable<bool> Refunds_Import { get; set; }
        public Nullable<bool> Refunds_Export { get; set; }
        public Nullable<bool> Returns_Import { get; set; }
        public Nullable<bool> Returns_Export { get; set; }
        public Nullable<bool> Billing_Import { get; set; }
        public Nullable<bool> Billing_Export { get; set; }
        public Nullable<bool> Cancellation_Import { get; set; }
        public Nullable<bool> Cancellation_Export { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Fk_ERPID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSubscription> CustomerSubscriptions { get; set; }
    }
}
