//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConnector
    {
        public int PK_AuthorizationID { get; set; }
        public Nullable<int> Fk_ConnectorID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public string UserConnectorName { get; set; }
        public string AuthorizationKeys { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> FK_IntegratorID { get; set; }
    
        public virtual Connector Connector { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
