//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webhook_Request
    {
        public int WR_ID { get; set; }
        public string Action_Name { get; set; }
        public string Status { get; set; }
        public string Request_Body { get; set; }
        public string Signature { get; set; }
    }
}
